Fixed Java SE Development Kit install.
- Oracle makes it difficult to download the Java SE Development Kit as
  an offline download because the license must be accepted first. The
  JDK is important to have installed as several Homebrew apps require
  it to exist first.
- This provides a prompt for checking that the Java SE Development Kit
  has been installed before proceeding as the original way of
  installing it assumed you had visited the Oracle web site and
  accepted the license.

diff --git a/bin/install_dev_tools b/bin/install_dev_tools
--- a/bin/install_dev_tools
+++ b/bin/install_dev_tools
@@ -6,11 +6,18 @@
 printf "Installing Xcode CLI tools...\n"
 xcode-select --install
 
-read -p "Have you completed the Xcode CLI tools install (y/n)? " response
-if [[ "$response" != "y" ]]; then
+read -p "Have you completed the Xcode CLI tools install (y/n)? " xcode_response
+if [[ "$xcode_response" != "y" ]]; then
   printf "ERROR: Xcode CLI tools must be installed before proceeding.\n"
   exit 1
 fi
 
-printf "Installing Java...\n"
-install_java "$JAVA_URL" "$JAVA_VOLUME_NAME"
+printf "Installing $JAVA_LABEL...\n"
+printf "%s\n" "You must manually accept the license and download the $JAVA_LABEL: $JAVA_DOWNLOAD_URL."
+open $JAVA_DOWNLOAD_URL
+
+read -p "Have you completed the $JAVA_LABEL install (y/n)? " java_response
+if [[ "$java_response" != "y" ]]; then
+  printf "ERROR: $JAVA_LABEL must be installed before proceeding.\n"
+  exit 1
+fi
